### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by AdhamHaisami** [GSG-G9/beauty-salon#4]
# Project setup

### server
 - Create a server folder with the following file structure
   server
│ app.js
│ index.js 
│
└───routes :
│   │   index.js
│   │   file1.js
│   │   file2.js
│   │   ...
│ 
└───controllers :
│       │   index.js
│       └───   folder1 :
│       │             │   index.js
│       │             │   file1.js
│       │             │      ...
│       └───  folder2 :
│       │             │   index.js
│       │             │   file1.js
│       │             │      ...
│       └───  common :
│       │             │   index.js
│       │             │   file1.js
│       │             │      ...
│       └───  errors :
│       │             │   index.js
│       │             │   file1.js
│       │             │      ...
│       │   ...
│   
└─── database :
│       └───   config :
│       │             │   bulid.js
│        │             │   connection.js
│       │             │   bulid.sql
│       │             │   fakeData.sql
│       └───  quieres :
│       │             │   index.js
│       │             │   file1.js
│       │             │      ...
│
└───utilities :
│   │   index.js
│   │   file1.js
│   │   file2.js
│   │   ...
└───middlewares :
│   │   index.js
│   │   file1.js
│   │   file2.js
│   │   ...
│ 

### Client
 - Create a client folder using `create-react-app` with the following file structure:
 client :
│
└───public :
│   │   index.html
│ 
└───src :
│       │   index.js
│       └───   assets :
│       │             │   file1.jpg
│       │             │      ...
│       └───  component :
│       │             │  index.js
│       │             └───  component1:
│       │             │           │ index.js
│       │             │           │ style.css
│       │             └───  component2:
│       │             │           │ index.js
│       │             │           │ style.css
│       │             │      ...
│       └───  pages :
│       │             │   index.js
│       │             └───  page1:
│       │             │           │ index.js
│       │             │           │ style.css
│       │             └───  page2:
│       │             │           │ index.js
│       │             │           │ style.css
│       │             │      ...
└───utilities :
│   │   index.js
│   │   file1.js
│   │   file2.js
│   │   ...

- Create a package.json using the 'npm init' command.
- Create a test folder

**Comment by mFlaifel** [comment]
please include the basic file structure tree include all files
you can [see this link](https://github.com/GSG-G9/MASA-Store/issues/5)

**Comment by AdhamHaisami** [comment]
> * please include the basic file structure tree including all files
>   you can [see this link](https://github.com/GSG-G9/MASA-Store/issues/5)

Done :+1:
